// M7 — Valeurs MOCK pour l'aperçu de notification (jamais de donnée réelle).
export const MOCK_NOTIFICATION_VARS: Record<string, string> = {
  sitename: 'Beauty Savage',
  firstname: 'Marie',
  lastname: 'Dupont',
  clientname: 'Marie Dupont',
  customername: 'Marie Dupont',
  servicename: 'Soin visage signature',
  formationname: 'Formation cils',
  productname: 'Sérum éclat',
  bookingdate: 'lundi 1 juillet 2026',
  bookingtime: '14:00',
  newbookingdate: 'mardi 2 juillet 2026',
  sessiondate: 'lundi 1 juillet 2026',
  sessiontime: '09:00',
  saleid: 'S-2026-0001',
  amount: '80,00 €',
  refundamount: '40,00 €',
  commissionamount: '210,00 €',
  optionscount: '2',
  period: 'juin 2026',
  month: 'juin',
  year: '2026',
  jobname: 'reminderJob',
};
