export const ACTIVE_SERVICE_BOOKING_STATUSES = ['pending_payment', 'confirmed'];
export const PENDING_PAYMENT_EXPIRATION_MINUTES = 30;

export const SERVICE_SLOT_ERROR_CODES = {
  SERVICE_NOT_BOOKABLE: 'SERVICE_NOT_BOOKABLE',
  PRACTITIONER_NOT_FOUND: 'PRACTITIONER_NOT_FOUND',
  PRACTITIONER_SERVICE_MISMATCH: 'PRACTITIONER_SERVICE_MISMATCH',
  INVALID_START_AT: 'INVALID_START_AT',
  INVALID_END_AT: 'INVALID_END_AT',
  INVALID_SLOT_RANGE: 'INVALID_SLOT_RANGE',
  INVALID_SLOT_DURATION: 'INVALID_SLOT_DURATION',
  SLOT_PAST: 'SLOT_PAST',
  SLOT_OUTSIDE_SCHEDULE: 'SLOT_OUTSIDE_SCHEDULE',
  SLOT_UNAVAILABLE: 'SLOT_UNAVAILABLE'
};

export function isActiveServiceBookingStatus(value) {
  return ACTIVE_SERVICE_BOOKING_STATUSES.includes(String(value || '').trim());
}
