// M6 — Valeurs MOCK pour l'aperçu (jamais d'adresse e-mail, jamais de donnée réelle).
// Uniquement des valeurs d'exemple pour rendre les variables {{...}} dans la preview.
export const MOCK_PREVIEW_VARS: Record<string, string> = {
  sitename: 'Beauty Savage',
  institutename: 'Beauty Savage',
  firstname: 'Marie',
  lastname: 'Dupont',
  customername: 'Marie Dupont',
  servicename: 'Soin visage signature',
  formationname: 'Formation cils',
  formationtitle: 'Formation cils',
  productname: 'Sérum éclat',
  bookingdate: 'lundi 1 juillet 2026',
  bookingtime: '14:00',
  bookingdatetime: 'lundi 1 juillet 2026 à 14:00',
  sessiondatelabel: 'lundi 1 juillet 2026',
  sessiontimelabel: '14:00',
  practitionername: 'Romane',
  cancellationdays: '7',
  timelabel: 'demain',
  bookingid: 'BKG-2026-0001',
  paymenttype: 'Paiement complet',
  depositamount: '30,00 €',
  remainingamount: '50,00 €',
  saleid: 'S-2026-0001',
  amount: '80,00 €',
  amountpaid: '80,00 €',
  invoicepageurl: 'https://exemple.test/facture',
  invoicedownloadurl: 'https://exemple.test/facture.pdf',
  refundamount: '40,00 €',
  refundstatus: 'confirmé',
  refunddatetime: '1 juillet 2026 15:00',
  refundid: 'RF-2026-0001',
  refundedatformatted: '1 juillet 2026',
  trackingurl: 'https://exemple.test/suivi',
  itemdetail: 'Soin visage — lundi 1 juillet 2026',
  reason: 'à votre demande',
  year: '2026',
  giftcardcode: 'GC-XXXX',
  giftcardbalance: '20,00 €',
  period: 'juin 2026',
  daystotal: '15',
  daysleft: '5',
  platformurl: 'https://exemple.test/plateforme',
  actionurl: 'https://exemple.test/action',
};
