// M3E/M4/M5/M6 — Espace Manager : clients API typés (supervision mail, identités, theme studio,
// templates e-mail).
export * from './mailSupervision';
export * from './communicationIdentities';
export * from './themeStudio';
export * from './mailTemplates';
export * from './notificationCategories';
export * from './notificationTemplates';
export * from './notifications';
export * from './calendar';
export * from './availability';
export * from './customer360';
export * from './finance';
export * from './commissionFinance';
export * from './giftCards';
export * from './giftCardTemplates';
export * from './giftCardLibrary';
export * from './manualBooking';
export * from './customerNotes';
export * from './catalogue';
export * from './learning';
export * from './homeSettings';
export * from './siteIdentity';
export * from './systemConfiguration';
export * from './mode';
export * from './managerUsers';
export * from './devDiagnostics';
export * from './integratedApi';
export * from './evaluations';
